# Generated by Django 3.1.5 on 2021-01-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0002_actors_heroes_narrative_producer_song'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Heroes',
            new_name='Actor',
        ),
        migrations.RenameModel(
            old_name='Actors',
            new_name='Hero',
        ),
    ]
